### ISSUE TITLE
Is it possible to make this work with background-image css?

### ISSUE THREAD

**Issue by thebspin** [robinloeffel/cosha#2]
Simply applying it to a div that has style background-image does nothing or could interfer because it wrapps it with a div and class.

**Comment by rbnts** [comment]
This won't be happening, as this is achievable with just good old CSS: https://www.reddit.com/r/webdev/comments/ffiw2h/ive_created_a_small_1kb_library_which_makes_the/fk02vzo/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
