### ISSUE TITLE
Hide background image for screen readers

### ISSUE THREAD

**Issue by kn0wn** [robinloeffel/cosha#3]
Because this library is duplicating the node, a screen reader would pass over both the images and repeat the callout. Therefore you need to add the attribute 'aria-hidden' on the background image.

`clone.setAttribute('aria-hidden', 'true');`

If you open up PR's I can create one, if not I have implemented it on [vue-cosha](https://github.com/kn0wn/vue-cosha) if you want to copy it over!

**Comment by rbnts** [comment]
Hey @kn0wn 

Thanks for taking the time and looking through the source and even porting the module to Vue!

I love your suggestion and will for sure implement it.
However, I will probably go the route of simply setting `alt=""` on the clone, as suggested here by the W3C: https://www.w3.org/WAI/tutorials/images/decorative/

What do you think?

Have a good one!

**Comment by kn0wn** [comment]
Wow, I didn't know that it would get skipped if the alt is empty - thanks for the info!
